---
k3s_server:
  write-kubeconfig-mode: "644"
  docker: false
  flannel-backend: "none"
  disable:
    - flannel                         # replaced with Tigera Operator Helm Chart
    - metrics-server                  # installed with Flux
    - servicelb                       # replaced with MetalLB Helm Chart
    - traefik                         # replaced with ingress-nginx Helm Chart
    - local-storage                   # replaced with EBS
    - coredns                          # replaced with Coredns Helm Chart

  disable-network-policy: true
  disable-cloud-controller: true
  disable-kube-proxy: true
  disable-helm-controller: false

  cluster-cidr: "{{ k3s_cluster_cidr }}"
  service-cidr: "{{ k3s_service_cidr }}"
  tls-san:
    - "{{ k3s_registration_address }}"

  kubelet-arg:
    - "image-gc-high-threshold=64"
    - "image-gc-low-threshold=55"
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"  # Required to monitor kube-controller-manager with kube-prometheus-stack
  kube-proxy-arg:
    - "metrics-bind-address=0.0.0.0" # Required to monitor kube-proxy with kube-prometheus-stack
  kube-scheduler-arg:
    - "bind-address=0.0.0.0" # Required to monitor kube-scheduler with kube-prometheus-stack
  k3s_extra_args:
    - "--kube-reserved=cpu=500m,memory=1Gi"
    - "--system-reserved=cpu=250m,memory=512Mi"
    - "--eviction-hard=memory.available<200Mi"
