---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: altinity-clickhouse-operator
      version: "0.25.5"
      sourceRef:
        kind: HelmRepository
        name: altinity
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    operator:
      create: true
      namespace: database
      image:
        repository: altinity/clickhouse-operator
        tag: "0.25.5"
        pullPolicy: IfNotPresent
    metrics:
      create: true
      namespace: database
      image:
        repository: altinity/metrics-exporter
        tag: "0.25.5"
        pullPolicy: IfNotPresent
    clickhouse:
      create: false # We'll create our own ClickHouseInstallation
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 512Mi
    watchNamespaces: []
    watchAllNamespaces: true
