---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: timcasa-me
spec:
  secretName: timcasa-me-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: timcasa.me
  dnsNames:
  - timcasa.me
  - "*.timcasa.me"
