---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: timcasa-me-tls
spec:
  secretStoreRefs:
  - name: onepassword
    kind: ClusterSecretStore
  selector:
    secret:
      name: timcasa-me-tls
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
  - match:
      secretKey: &key tls.crt
      remoteRef:
        remoteKey: timcasa-me-tls
        property: *key
  - match:
      secretKey: &key tls.key
      remoteRef:
        remoteKey: timcasa-me-tls
        property: *key
