---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: clickhouse-config-logger
  files:
  - config.d/logger.xml
- name: clickhouse-config-path
  files:
  - config.d/path.xml
- name: clickhouse-config-server
  files:
  - config.d/server.xml
- name: clickhouse-config-users
  files:
  - config.d/users.xml

resources:
- ./dnsendpoint.yaml
- ./tcproute.yaml
- ./externalsecret.yaml
- ./clickhouse-installation.yaml
