k3s_cluster:
  children:
    server:
      hosts:
        quasar:
          ansible_host: 192.168.1.13
        nexus:
          ansible_host: 192.168.1.9
        atlas:
          ansible_host: 192.168.1.12
  vars:
    ansible_port: 22
    ansible_user: spike
