all:
  children:
    kubernetes:
      hosts:
        nexus:
          ansible_host: 192.168.1.9
        atlas:
          ansible_host: 192.168.1.12
      children:
        controller:
          hosts:
            nexus: {}
            atlas: {}
        worker:
          hosts:
            nexus: {}
            atlas: {}
