---
- name: Prepare debian servers
  hosts: kubernetes
  any_errors_fatal: true
  become: true
  gather_facts: true

  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2

  roles:
    - name: Prepare debian servers
      role: os
