---
collections:
- name: community.general
  version: 9.5.0
- name: ansible.utils
  version: 5.1.2
- name: kubernetes.core
  version: 5.0.0
- name: ansible.posix
  version: 1.6.1
- name: https://github.com/k3s-io/k3s-ansible.git
  type: git
  version: 1.1.1
