---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clickhouse-operator
spec:
  interval: 1h
  path: ./kubernetes/apps/database/clickhouse-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clickhouse-cluster
spec:
  dependsOn:
  - name: external-secrets
    namespace: external-secrets
  - name: clickhouse-operator
    namespace: database
  - name: longhorn
    namespace: storage
  interval: 1h
  wait: true
  prune: true
  path: ./kubernetes/apps/database/clickhouse-operator/cluster
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
